name: sandbox_py311
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pycares=4.11.0
  - numba=0.63
  - llvmlite=0.46.0   # pin if needed
  - pip
  - pip:
      - pandas==2.2.0
      - aiohttp==3.13.2
      - torch==2.2.2

