name: /Users/ahmadjankhattak/Code/workflows/sandbox_build/venv/venv_sandbox_py3.11
channels:
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _openmp_mutex=4.5=7_kmp_llvm
  - bzip2=1.0.8=h6c40b1e_6
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - cffi=1.17.1=py311h9205ec4_1
  - expat=2.7.1=h6d0c2b6_0
  - icu=75.1=h120a0e1_0
  - libblas=3.11.0=4_he492b99_openblas
  - libcblas=3.11.0=4_h9b27e0a_openblas
  - libcxx=21.1.7=h3d58e20_0
  - libexpat=2.7.1=h21dd04a_0
  - libffi=3.4.4=hecd8cb5_1
  - libgcc=15.2.0=h08519bb_15
  - libgfortran=15.2.0=h7e5c614_15
  - libgfortran5=15.2.0=hd16e46c_15
  - liblapack=3.11.0=4_h859234e_openblas
  - liblzma=5.8.1=hd471939_2
  - liblzma-devel=5.8.1=hd471939_2
  - libopenblas=0.3.30=openmp_h6006d49_4
  - libsqlite=3.51.1=h6cc646a_0
  - libzlib=1.3.1=hd23fc13_2
  - llvm-openmp=21.1.7=h472b3d1_0
  - llvmlite=0.46.0=py311hb26b958_0
  - ncurses=6.5=h923df54_0
  - numba=0.63.0=py311hfe9595b_0
  - openssl=3.6.0=h230baf5_0
  - pip=25.3=pyhc872135_0
  - pycares=4.11.0=py311hf197a57_1
  - pycparser=2.21=pyhd3eb1b0_0
  - python=3.11.11=h9ccd52b_2_cpython
  - python_abi=3.11=8_cp311
  - readline=8.3=h49f2429_0
  - sqlite=3.51.1=h9e4bfbb_0
  - tk=8.6.13=hf689a15_3
  - wheel=0.45.1=py311hecd8cb5_0
  - xz=5.8.1=h357f2ed_2
  - xz-gpl-tools=5.8.1=h357f2ed_2
  - xz-tools=5.8.1=hd471939_2
  - zlib=1.3.1=hd23fc13_2
  - zstd=1.5.7=h3eecb57_6
  - pip:
      - affine==2.4.0
      - aiodns==3.6.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiohttp-client-cache==0.14.2
      - aiosignal==1.4.0
      - aiosqlite==0.21.0
      - arch==8.0.0
      - async-retriever==0.17.1
      - attrs==25.4.0
      - backports-zstd==1.2.0
      - black==25.12.0
      - blosc2==3.12.2
      - bmipy==2.0.1
      - branca==0.8.2
      - brotli==1.2.0
      - cattrs==25.3.0
      - certifi==2025.11.12
      - cftime==1.6.5
      - charset-normalizer==3.4.4
      - click==8.3.1
      - click-plugins==1.1.1.2
      - cligj==0.7.2
      - contourpy==1.3.3
      - cycler==0.12.1
      - cython==3.2.2
      - cytoolz==1.1.0
      - defusedxml==0.7.1
      - deprecated==1.3.1
      - f90nml==1.5.0
      - filelock==3.20.0
      - fiona==1.10.1
      - folium==0.20.0
      - fonttools==4.61.0
      - frozenlist==1.8.0
      - fsspec==2025.12.0
      - geojson-pydantic==0.7.0
      - geopandas==1.1.1
      - h5netcdf==1.7.3
      - h5py==3.15.1
      - hydrosignatures==0.17.1
      - hydrotools--restclient==4.1.0
      - hydrotools-events==2.2.0
      - hydrotools-metrics==2.2.0
      - hydrotools-nwis-client==4.1.0
      - hypy==0.0.3
      - idna==3.11
      - itsdangerous==2.2.0
      - jinja2==3.1.6
      - joblib==1.5.2
      - kiwisolver==1.4.9
      - lstm==1.1.0
      - lxml==6.0.2
      - markupsafe==3.0.3
      - matplotlib==3.10.8
      - mpmath==1.3.0
      - msgpack==1.1.2
      - multidict==6.7.0
      - mypy-extensions==1.1.0
      - ndindex==1.10.1
      - netcdf4==1.6.3
      - networkx==3.6.1
      - ngen-cal==0.2.2
      - ngen-cal-user-plugins==0.1
      - ngen-config==0.3.0
      - ngen-config-gen==0.0.2
      - ngen-init-config==0.0.7
      - numexpr==2.14.1
      - numpy==1.26.4
      - owslib==0.35.0
      - packaging==25.0
      - pandas==2.2.0
      - pathspec==0.12.1
      - patsy==1.0.2
      - pillow==12.0.0
      - platformdirs==4.5.1
      - pluggy==1.6.0
      - propcache==0.4.1
      - py-cpuinfo==9.0.0
      - pyarrow==11.0.0
      - pydantic==1.10.24
      - pygeohydro==0.17.1
      - pygeoogc==0.17.1
      - pygeoutils==0.17.1
      - pynhd==0.17.1
      - pyogrio==0.12.1
      - pyparsing==3.2.5
      - pyproj==3.7.2
      - python-dateutil==2.9.0.post0
      - python-forge==18.6.0
      - pytokens==0.3.0
      - pytz==2025.2
      - pyyaml==6.0.3
      - pyyml==0.0.2
      - rasterio==1.4.3
      - requests==2.32.5
      - requests-cache==1.2.1
      - rioxarray==0.19.0
      - sandbox==0.3.0
      - scipy==1.16.3
      - setuptools==68.2.2
      - shapely==2.1.2
      - six==1.17.0
      - statsmodels==0.14.6
      - sympy==1.14.0
      - tables==3.10.2
      - tomli==2.3.0
      - tomli-w==1.2.0
      - toolz==1.1.0
      - torch==2.2.2
      - typing-extensions==4.15.0
      - tzdata==2025.2
      - ujson==5.11.0
      - url-normalize==2.2.1
      - urllib3==2.6.1
      - wrapt==2.0.1
      - xarray==2025.12.0
      - xyzservices==2025.11.0
      - yarl==1.22.0
prefix: /Users/ahmadjankhattak/Code/workflows/sandbox_build/venv/venv_sandbox_py3.11
